### ISSUE TITLE
Guess My Number

### ISSUE THREAD

**Issue by sparshiigupta** [anjali1102/Hacktober2021#107]
# Details
A random number will be generated by the computer and the player will have to guess it.

**Comment by anjali1102** [comment]
Is it python/ JS peoject

**Comment by anjali1102** [comment]
?

**Comment by sparshiigupta** [comment]
JS project

**Comment by Kevinjadia** [comment]
Can you assign me this issue? Let me make it clear, is it like we need to make a python program in which one random number will be generated and user has to guess what the number will be if it's true program ends else user will get n no of chances to guess right?
