### ISSUE TITLE
song-lyrics-app

### ISSUE THREAD

**Issue by chinmayaAgrawal** [anjali1102/Hacktober2021#108]
# Song-Lyrics-Search-App

A browser based application using JavaScript to search songs, artists and lyrics by typing out the singer's name using the [lyrics.ovh](https://lyrics.ovh) API .

<hr>

## Technologies Used

``` JavaScript, Html, CSS ```

<hr>

## API

``` lyrics.ovh ```

<hr>

## Project Specifications

- Displayed UI with song/artist input
- Fetch songs/artists and put in DOM using ``` lyrics.ovh ``` API.
- Added pagination .
- Added get lyrics functionality and display functions in DOM

![Screenshot (738)](https://user-images.githubusercontent.com/54171759/137794915-ee7469d2-ff02-4b3a-baaa-09a6094f71a7.png)
![Screenshot (739)](https://user-images.githubusercontent.com/54171759/137794942-f39dc894-de64-4e05-87d8-c4ed037c48b9.png)

<hr>

## Alternatives considered
- react app but will be wat to heavy and lots of dependencies

**Comment by anjali1102** [comment]
Go ahead, 

**Add deployed link in project readme**
